/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32l476xx.h"
#include <stdint.h>

void __systemClock_Config_40MHz(void);

int main(void)
{
    /* Loop forever */
	for(;;);
}

/**
 * @brief __systemClock_Config_40MHz() is used for initialization and configuration
 *        of main system clock (SYSCLK) to a value of 40 MHz using HSE nad PLL.
 *
 * @param void
 * @return None
 */
void __systemClock_Config_40MHz(void) {

    RCC->APB1ENR1 |= RCC_APB1ENR1_PWREN; 
    PWR->CR1 |= PWR_CR1_VOS_0; /* Set greater voltage value */

    RCC->CR |= RCC_CR_HSEON; /* Turn on the External Quarz Oscilator */
    while(!(RCC->CR & RCC_CR_HSERDY)); /* Wait for the HSERDY bit to set*/

    /* 2WS, because 40MHz, turn the prefetched on, turn the cache on for instructions, turn cache on for data */
    FLASH->ACR = FLASH_ACR_LATENCY_2WS | FLASH_ACR_PRFTEN | FLASH_ACR_ICEN | FLASH_ACR_DCEN; /* Configure Flash */

    /* Configure PLL -> ((ext) 8MHz / 2) * 20 / 2 = 40MHz */
    RCC->PLLCFGR = RCC_PLLCFGR_PLLSRC_HSE | 2 << RCC_PLLCFGR_PLLM_Pos | 20 << RCC_PLLCFGR_PLLN_Pos | 0 << RCC_PLLCFGR_PLLR_Pos | RCC_PLLCFGR_PLLREN;
    /* HSE clock selected as PLL, ... , clock entry (11 to [Bit1 and Bit0]) */
    /* PLLM = 2, PLLN = 20, PLLR = 2 => 40MHz */

    RCC->CR |= RCC_CR_PLLON; /* Turn on the PLL */
    while(!(RCC->CR & RCC_CR_PLLRDY)); /* Wait for the PLLRDY bit to set */

    RCC->CFGR &= ~(RCC_CFGR_HPRE | RCC_CFGR_PPRE1 | RCC_CFGR_PPRE2); /* Clear prescalers for clocks */
    RCC->CFGR |= RCC_CFGR_HPRE_DIV1 | RCC_CFGR_PPRE1_DIV1 | RCC_CFGR_PPRE2_DIV1; /* Set prescalers for clocks to 1 */  

    RCC->CFGR |= RCC_CFGR_SW_PLL; /* Select PLL as system clock*/
    while(!(RCC->CFGR & RCC_CFGR_SWS_PLL)); /* Wait for switch of systemclock to PLL*/

    SystemCoreClock = 40000000; /* Change SystemCoreClock variable to set value */

    return;
}