/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "gpio.h"
#include "clock.h"
#include "systick.h"

#include <stdint.h>

int main(void)
{
    SystemClock_Config_24MHz();
    GPIOx_Init();
    SysTick_Init();

    /* Loop forever */
    uint32_t tick = 0;
    uint32_t last_tick = 0;

	for(;;) {

        tick = get_SysTick();
        if (tick - last_tick >= 1000) {
            last_tick = tick;
            GPIO_TogglePin(GPIOA, 5);
        }
    };
}
